CREATE TABLE all_vitals (
    all_vitals_id       INT,
    patient_id          VARCHAR(50),
    emr_id              VARCHAR(25),
    encounter_id        VARCHAR(50),
    visit_id            VARCHAR(50),
    encounter_location  VARCHAR(255),
    encounter_datetime  DATETIME,
    provider            VARCHAR(255),
    date_entered        DATETIME,
    user_entered        VARCHAR(255),
    height              FLOAT,
    weight              FLOAT,
    temperature         FLOAT,
    heart_rate          FLOAT,
    respiratory_rate    FLOAT,
    bp_systolic         FLOAT,
    bp_diastolic        FLOAT,
    o2_saturation       FLOAT,
    muac_mm             FLOAT,
    random_glucose      FLOAT,
    fasting_glucose     FLOAT,
    chief_complaint     TEXT,
    index_asc           INT,
    index_desc          INT
);
